### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by ItzBaka** [itsxScrubz/poe-discord-helper#1]
Hayo, just created my bot but I have problems with setting it up, in which directory do I have to go? how do I create a .env file?

Thanks a lot! and hyped for your overlay :)

**Comment by itsxScrubz** [comment]
When starting the bot, you just CD into the root directory and run the yarn start or npm run start command.
As for the .env file, you just create a file named .env inside the root directory. You can create it the same way you would any file.

**Comment by ItzBaka** [comment]
Mhh nah.. somehow i dont know what to do, never done a discord bot.. so well only have problems with setting it up

**Comment by itsxScrubz** [comment]
Add me on discord and I'll walk you thru it.
Scrubz#0001
